### ISSUE TITLE
Feature request: Limiting actions to specific a doctype

### ISSUE THREAD

**Issue by sebastiandammark** [afabri73/AF-Auto-Populate-Properties#2]
As it is right now, an action works across all doctypes.
So if you have an action looking like this:
`{
"propertyAlias": "title",
"config": {
"propertyType": "string",
"propertyAliasToCopyValue": "Name",
"defaultValue": ""
}
}`

It will be applied across all doctypes through the entire umbraco installation.
If we could add `"documentTypeAlias": "articlePage"` to the action, then we could limit the action to that document type.

**Comment by afabri73** [comment]
As I wrote in the readme, I have planned this new feature in the next release.
I want to manage the grouping of properties for each document type. ;-)

**Comment by afabri73** [comment]
Published new v7.1.0.0 with doctype support
